type Query {
  health: String!
}

input LoginInput {
  email: String!
  password: String!
}
input CreateUserInput {
  firstName:String!
  lastName:String!,
  email:String!
  password:String!
  role:Role!
}
enum Role {
  Admin
  HR
  Manager
  Employee
}

type User {
  id: ID!
  email: String!
  firstName: String!
  lastName: String!
  role: String!
  password:String
  isActive: Boolean
  isVerified: Boolean
}

type LoginResponse {
  accessToken: String!
  refreshToken: String!
  user:User
}
type ContextResponse {
  id:String
  email:String
  role:Role
}

type Mutation {
  login(input: LoginInput!): LoginResponse!
  createUser(input: CreateUserInput!): User!
}
type Query {
  me:ContextResponse
}